services:
  # --- BASE DE DATOS ---
  db:
    image: postgres:15
    container_name: ${APP_NAME:-mi-app}-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - red-interna

  # --- APLICACIÓN ---
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-mi-app}
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
    networks:
      - red-internet
      - red-interna
    depends_on:
      - db

networks:
  red-internet:
    external: true
  red-interna:
    external: true

volumes:
  db_data:
