services:
  # --- PROXY INVERSO ---
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - red-internet
    restart: always

  # --- SSL AUTOMÁTICO ---
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=carmengarcianavarro19@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy
    networks:
      - red-internet
    restart: always

  # --- GESTIÓN ---
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.mcarmen.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.mcarmen.servidorgp.somosdelprieto.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - red-internet
      - red-interna

  # --- MONITORIZACIÓN ---
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    environment:
      - VIRTUAL_HOST=prometheus.mcarmen.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=prometheus.mcarmen.servidorgp.somosdelprieto.com
    networks:
      - red-internet
      - red-interna

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - red-interna

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - VIRTUAL_HOST=grafana.mcarmen.servidorgp.somosdelprieto.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.mcarmen.servidorgp.somosdelprieto.com
    networks:
      - red-internet
      - red-interna

networks:
  red-internet:
    external: true
  red-interna:
    external: true

volumes:
  portainer_data:
  grafana_data:
  prometheus_data:
  certs:
  vhost:
  html:
  acme:
