services:
  amazon-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amazonapi
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: appprueba.servidorgp.somosdelprieto.com
      VIRTUAL_PORT: "8080"
      # LETSENCRYPT_HOST: appprueba.servidorgp.somosdelprieto.com  # SSL desactivado temporalmente

      # H2 persistente dentro del contenedor: /data se guarda en el volumen amazonapi_data.
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/amazonapi.db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"
      SERVER_PORT: "8080"
    volumes:
      - amazonapi_data:/data
    networks:
      - red-internet

networks:
  red-internet:
    external: true

volumes:
  amazonapi_data: